window.DUODECIMA_GODS = [
  // ===== KITS PUBLICADOS NO GUIA (31/08/2026) =====
  {id:'iuppiter',name:'Iuppiter Optimus Maximus',group:'Triunviro',source:'Guia atual',casting:'fe',hpBase:25,hpPerDecade:5,bonuses:{fe:1,for:1,con:2},skillChoice:['Intimidação','Atletismo'],resource:{name:'Raiva do Trovão',maxFormula:'8 + floor(nível/10)',max:(lvl)=>8+Math.floor(lvl/10)},notes:['Triunviro: +2 CON, +1 FÉ e +1 FOR. Escolha divina entre Intimidação ou Atletismo.']},
  {id:'juno',name:'Juno Mater',group:'Dii Consentis',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,car:1},grantedSkills:['Intuição'],notes:['Kit de devoção de Juno Mater.']},
  {id:'ceres',name:'Ceres',group:'Dii Consentis',source:'Guia atual',casting:'fe',hpBase:25,hpPerDecade:5,bonuses:{con:2,fe:1},grantedSkills:['Natureza']},
  {id:'marte',name:'Marte Ultor',group:'Dii Consentis',source:'Guia atual',casting:'con',hpBase:25,hpPerDecade:6,bonuses:{for:2,con:1},grantedSkills:['Atletismo']},
  {id:'febo',name:'Febo',group:'Dii Consentis',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,fe:1},skillChoice:['Atuação','Manipulação','Intimidação','Persuasão'],notes:['A bonificação divina concede 1 perícia de Carisma à escolha. Dons do Sol concede escolhas adicionais e será ligado ao import completo das passivas.']},
  {id:'diana',name:'Diana',group:'Dii Consentis',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{des:2,con:1},grantedSkills:['Agilidade'],notes:['Caçadoras de Diana. Dons da Lua concede 2 perícias adicionais; será ligado ao import completo das passivas.']},
  {id:'venus',name:'Vênus',group:'Dii Consentis',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,des:1},grantedSkills:['Persuasão']},
  {id:'mercurio',name:'Mercúrio',group:'Dii Consentis',source:'Guia atual',casting:'des',hpBase:20,hpPerDecade:5,bonuses:{des:2,car:1},grantedSkills:['Mãos Leves']},
  {id:'baco',name:'Baco',group:'Dii Consentis',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,des:1},grantedSkills:['Tolerância']},
  {id:'vesta',name:'Vesta',group:'Dii Consentis',source:'Guia atual',casting:'fe',hpBase:25,hpPerDecade:6,bonuses:{for:2,con:1},grantedSkills:['Tolerância']},
  {id:'summanus',name:'Summanus',group:'Triunviro',source:'Guia atual',casting:'fe',hpBase:22,hpPerDecade:4,bonuses:{int:2,fe:1,des:1},skillChoice:['Intimidação','Furtividade'],resource:{name:'Carga Noturna',maxFormula:'10',max:()=>10}},
  {id:'plutao',name:'Plutão / Dis Pater',group:'Triunviro',source:'Guia atual',casting:'car',hpBase:25,hpPerDecade:5,bonuses:{con:2,fe:1,car:1},skillChoice:['Intimidação','Intuição'],resource:{name:'Acúmulo Necromântico',maxFormula:'10',max:()=>10}},
  {id:'fantaso',name:'Fântaso',group:'Dii Inferi',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,fe:1},grantedSkills:['Intuição']},
  {id:'trivia',name:'Trivia',group:'Dii Inferi',source:'Guia atual',casting:'int',hpBase:20,hpPerDecade:5,bonuses:{int:2,fe:1},grantedSkills:['Conhecimento Mágico'],notes:['Trivia só tem filhas mulheres.']},
  {id:'somnos',name:'Somnos',group:'Dii Inferi',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,int:1},grantedSkills:['Conhecimento Mítico']},
  {id:'fobetor',name:'Fobetor',group:'Dii Inferi',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{con:2,car:1},grantedSkills:['Intimidação'],resource:{name:'Desesperança',maxFormula:'5 + floor(nível/10)',max:(lvl)=>5+Math.floor(lvl/10)}},
  {id:'aquilon',name:'Aquilon',group:'Ventis',source:'Atualizado enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{des:2,con:1},grantedSkills:['Intimidação'],resource:{name:'Dança dos Ventos',maxFormula:'20 (barra coletiva)',max:()=>20},notes:['Este arquivo substitui a versão publicada no Guia.']},
  {id:'cupido-inanis',name:'Cupido Inanis',group:'Outros',source:'Guia atual',casting:'car',hpBase:18,hpPerDecade:4,bonuses:{car:2,int:1},grantedSkills:['Manipulação']},
  {id:'laetitia',name:'Laetitia',group:'Numina',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,des:1},grantedSkills:['Atuação']},
  {id:'bellona',name:'Bellona',group:'Outros',source:'Guia atual',casting:'con',hpBase:25,hpPerDecade:7,bonuses:{for:2,con:1},grantedSkills:['Atletismo']},
  {id:'netuno',name:'Netuno',group:'Triunviro',source:'Guia atual',casting:'fe',hpBase:25,hpPerDecade:5,bonuses:{des:2,fe:1,car:1},skillChoice:['Acrobacia','Atletismo'],resource:{name:'Maré Crescente',maxFormula:'10',max:()=>10}},
  {id:'letum',name:'Letum',group:'Dii Inferi',source:'Guia atual',casting:'fe',hpBase:25,hpPerDecade:5,bonuses:{for:2,car:1},grantedSkills:['Intimidação'],resource:{name:'Ruína',maxFormula:'5',max:()=>5}},
  {id:'somnia',name:'Somnia',group:'Dii Inferi',source:'Guia atual',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,des:1},grantedSkills:['Manipulação'],resource:{name:'Esperança Dourada',maxFormula:'5 + floor(nível/10)',max:(lvl)=>5+Math.floor(lvl/10)}},
  {id:'silvano',name:'Protegidos de Silvano',group:'Outros',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{con:2,fe:1},grantedSkills:['Sobrevivência'],notes:['Protegidos de Silvano são ninfas ou espíritos silvestres.']},
  {id:'cimopoleia',name:'Cimopoleia',group:'Outros',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,con:1},skillChoice:['Sobrevivência','Intimidação'],notes:['Filhos de Cimopoleia são considerados criaturas monstruosas.']},
  {id:'jano',name:'Jano',group:'Numina',source:'Guia atual',casting:'int',hpBase:20,hpPerDecade:5,bonuses:{int:2,fe:1},grantedSkills:['Intuição']},
  {id:'vis',name:'Vis',group:'Alati',source:'Guia atual',casting:'for',hpBase:30,hpPerDecade:5,bonuses:{for:2,con:1},grantedSkills:['Intimidação'],resource:{name:'Imperium',maxFormula:'10 (barra coletiva Alati)',max:()=>10}},
  {id:'potestas',name:'Potestas',group:'Alati',source:'Guia atual',casting:'car',hpBase:25,hpPerDecade:5,bonuses:{car:2,int:1},grantedSkills:['Intimidação'],resource:{name:'Imperium',maxFormula:'10 (barra coletiva Alati)',max:()=>10}},
  {id:'aemulatio',name:'Aemulatio',group:'Alati',source:'Guia atual',casting:'int',hpBase:25,hpPerDecade:5,bonuses:{int:2,con:1},skillChoice:['Percepção','Estratégia'],resource:{name:'Imperium',maxFormula:'10 (barra coletiva Alati)',max:()=>10},notes:['“Estratégia” aparece assim no kit publicado; mantida sem normalização automática.']},
  {id:'victoria',name:'Victoria',group:'Alati',source:'Guia atual',casting:'car',hpBase:25,hpPerDecade:5,bonuses:{des:2,car:1},skillChoice:['Agilidade','Intimidação'],resource:{name:'Imperium',maxFormula:'10 (barra coletiva Alati)',max:()=>10}},
  {id:'laverna',name:'Laverna',group:'Dii Inferi',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,car:1},grantedSkills:['Conhecimento Mágico']},
  {id:'libitina',name:'Libitina',group:'Dii Inferi',source:'Guia atual',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,con:1},grantedSkills:['Conhecimento Religioso'],notes:['O Guia chama a perícia de “Religião”; nesta base foi ligada ao nome vigente “Conhecimento Religioso”.']},

  // ===== KITS FORNECIDOS DIRETAMENTE PELA USUÁRIA =====
  {id:'vulcano',name:'Vulcano',group:'Dii Consentis',source:'Provisório enviado pela usuária',casting:'int',hpBase:33,hpPerDecade:5,bonuses:{con:2,for:1},grantedSkills:['Tolerância'],notes:['Kit desatualizado/provisório. O HP especial foi preservado conforme o arquivo recebido.']},
  {id:'proserpina',name:'Proserpina',group:'Dii Inferi',source:'Provisório enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,con:1},grantedSkills:['Natureza'],resource:{name:'Carga Crepuscular',maxFormula:'2/3/4 conforme estacas de Acúmulo Crepuscular',max:()=>4},notes:['O arquivo provisório contém uma sugestão alternativa de bônus; esta base usa a configuração principal escrita antes da sugestão.','O máximo efetivo de Carga Crepuscular é 2, 3 ou 4 conforme as estacas da passiva Acúmulo Crepuscular.']},
  {id:'mors',name:'Mors',group:'Dii Inferi',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,con:1},grantedSkills:['Furtividade'],notes:['Tocados por Mors não são filhos diretos; a relação é uma marca no nascimento.']},
  {id:'fortuna',name:'Fortuna',group:'Numina',source:'Provisório enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2},skillBonuses:{'Agilidade':1},grantedSkills:['Mãos Leves'],notes:['O arquivo recebido diz “+1 em Agilidade”. Como Agilidade é perícia, o +1 foi mantido como bônus de perícia, sem transformar silenciosamente em Destreza.']},
  {id:'discordia',name:'Discórdia',group:'Numina',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,int:1},grantedSkills:['Manipulação']},
  {id:'invidia',name:'Invidia',group:'Numina',source:'Provisório enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{car:2,int:1},grantedSkills:['Enganação'],notes:['O arquivo provisório usa “Enganação”, que não consta na lista-base atual de perícias. Mantida como perícia divina customizada até o rework.']},
  {id:'arcus',name:'Arcus',group:'Numina',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,des:1},grantedSkills:['Sobrevivência']},
  {id:'timor',name:'Timor',group:'Numina',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{for:2,car:1},grantedSkills:['Intimidação']},
  {id:'metus',name:'Metus',group:'Numina',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,con:1},grantedSkills:['Intimidação'],resource:{name:'Tensão',maxFormula:'depende das estacas do kit provisório',max:()=>4}},
  {id:'fama',name:'Fama',group:'Numina',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,int:1},grantedSkills:['Conhecimento Histórico']},
  {id:'angerona',name:'Angerona',group:'Numina',source:'Provisório enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{int:2,fe:1},grantedSkills:['Percepção']},
  {id:'angitia',name:'Angitia',group:'Numina',source:'Provisório enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,con:1},grantedSkills:['Medicina']},
  {id:'concordia',name:'Concordia',group:'Numina',source:'Provisório enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,fe:1},grantedSkills:['Persuasão']},
  {id:'juventas',name:'Juventas',group:'Dii Consentis',source:'Atualizado enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{con:2,fe:1},grantedSkills:['Medicina']},
  {id:'aeolos',name:'Aeolos',group:'Outros',source:'Atualizado enviado pela usuária',casting:'car',hpBase:20,hpPerDecade:5,bonuses:{car:2,int:1},grantedSkills:['Persuasão'],notes:['Aeolos interage com a Dança dos Ventos, mas não é Venti, não consome a barra e não libera Rajada Primordial.']},
  {id:'auster',name:'Auster',group:'Ventis',source:'Atualizado enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{des:2,for:1},grantedSkills:['Tolerância'],resource:{name:'Dança dos Ventos',maxFormula:'20 (barra coletiva)',max:()=>20}},
  {id:'favonio',name:'Favônio',group:'Ventis',source:'Atualizado enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{des:2,car:1},grantedSkills:['Natureza'],resource:{name:'Dança dos Ventos',maxFormula:'20 (barra coletiva)',max:()=>20}},
  {id:'vulturnos',name:'Vulturnos',group:'Ventis',source:'Atualizado enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{des:2,fe:1},grantedSkills:['Intimidação'],resource:{name:'Dança dos Ventos',maxFormula:'20 (barra coletiva)',max:()=>20}},
  {id:'justitia',name:'Justitia',group:'Numina',source:'Provisório enviado pela usuária',casting:'fe',hpBase:20,hpPerDecade:5,bonuses:{fe:2,int:1},grantedSkills:['Intuição']}
];

window.DUODECIMA_EXCLUDED_GODS = [
  {name:'Minerva',reason:'Sem kit; só será implementada quando o primeiro devoto ferrenho surgir no servidor.'},
  {name:'Volúpia',reason:'Ignorada por enquanto por instrução da usuária.'},
  {name:'Cloacina',reason:'Ignorada por enquanto por instrução da usuária.'}
];
