window.DUODECIMA_TALENTS = [
  {id:'ataque-extra',name:'Ataque Extra',minLevel:30,description:'Pode realizar um ataque adicional no próprio turno.',repeatable:true},
  {id:'expert',name:'Expert',minLevel:1,description:'Talento vigente no sistema; o efeito específico deve ser registrado conforme a versão aprovada pela staff.',repeatable:true,manual:true},
  {id:'perito',name:'Perito',minLevel:1,description:'Ganha 3 perícias adicionais à escolha.',repeatable:true,params:['skill1','skill2','skill3']},
  {id:'defensor',name:'Defensor',minLevel:1,description:'Recebe +1 na rolagem de Defesa e +1 em Resistências.',repeatable:true,automation:'defense'},
  {id:'comandante',name:'Comandante',minLevel:30,description:'Uma vez por turno, quando fizer um ataque, um aliado pode realizar um ataque contra o mesmo alvo.',repeatable:true},
  {id:'lingua-de-prata',name:'Língua de Prata',minLevel:1,description:'Talento vigente no sistema; registre o efeito específico aprovado pela staff sem confundir com passivas divinas de mesmo nome.',repeatable:true,manual:true},
  {id:'interceptador',name:'Interceptador',minLevel:1,description:'Uma vez por rodada, reduz 1d8 + BP do dano recebido por um aliado próximo.',repeatable:true},
  {id:'duelista',name:'Duelista',minLevel:1,description:'Recebe +2 de dano usando uma arma corpo a corpo em uma mão e sem escudo.',repeatable:true},
  {id:'campeao',name:'Campeão',minLevel:1,description:'Reduz permanentemente em 1 a margem necessária para Acerto Crítico.',repeatable:true},
  {id:'sortudo',name:'Sortudo',minLevel:1,description:'Permite rerrolar um d20 até 2 vezes por cena ou missão.',repeatable:true},
  {id:'inspirado',name:'Inspirado',minLevel:1,description:'Uma vez por turno, pode rolar 1d6 adicional e somar a um d20 já rolado.',repeatable:true},
  {id:'curandeiro',name:'Curandeiro',minLevel:1,description:'Aumenta os valores curados gradativamente por nível. O valor exato continua sendo aplicado conforme a regra vigente.',repeatable:true,manual:true},
  {id:'querido',name:'Querido',minLevel:60,description:'Buffs concedidos a aliados duram 1 turno adicional.',repeatable:true},
  {id:'chato',name:'Chato',minLevel:60,description:'Ao aplicar um debuff, a penalidade concedida por ele piora em 1.',repeatable:true},
  {id:'beijo-fortuna',name:'Beijo de Fortuna',minLevel:1,description:'Não sofre Falha Crítica: um 1 natural é tratado como 2.',repeatable:true},
  {id:'adepto-elemental',name:'Adepto Elemental',minLevel:1,description:'Causa +2 de dano fixo com poderes de um elemento escolhido.',repeatable:true,params:['element']},
  {id:'resiliente',name:'Resiliente',minLevel:1,description:'Adiciona BP aos testes de Resistência de um atributo escolhido.',repeatable:true,params:['attribute']},
  {id:'bruto',name:'Bruto',minLevel:1,description:'Usa Constituição no lugar de Destreza como atributo-base da Defesa.',repeatable:true,automation:'defense-constitution'},
  {id:'agil',name:'Ágil',minLevel:1,description:'Adiciona metade do bônus de Agilidade à Defesa, conforme a regra vigente.',repeatable:true,manual:true},
  {id:'aumento-atributo',name:'Aumento de Atributo',minLevel:1,description:'Concede +1 permanente em um atributo base, respeitando o limite de 5 da camada não divina.',repeatable:true,params:['attribute'],automation:'attribute'},
  {id:'pau-toda-obra',name:'Pau pra Toda Obra',minLevel:1,description:'Recebe +1d4 passivo em Testes de Perícia. O d4 não é convertido em bônus fixo.',repeatable:true},
  {id:'mestre-armas',name:'Mestre das Armas',minLevel:1,description:'Pode rerrolar resultados 1 e 2 nos dados de dano de armas físicas.',repeatable:true},
  {id:'invocador',name:'Invocador',minLevel:30,description:'Pode manifestar +1 invocação adicional por uso de magias e habilidades compatíveis.',repeatable:true},
  {id:'corpo-saudavel',name:'Corpo Saudável',minLevel:1,description:'Concede resistência contra veneno e fogo.',repeatable:true},
  {id:'duravel',name:'Durável',minLevel:1,description:'Soma Constituição novamente ao HP inicial e a cada progressão de 10 níveis.',repeatable:true,automation:'hp'},
  {id:'mestre-habilidades',name:'Mestre das Habilidades',minLevel:60,description:'Quando possui Vantagem em Habilidades, rola 3 dados em vez de 2.',repeatable:true},
  {id:'chef',name:'Chef',minLevel:1,description:'Durante um descanso, prepara uma refeição que concede 1d8 + BP de HP temporário.',repeatable:true},
  {id:'gambito-ofensivo',name:'Gambito Ofensivo',minLevel:1,description:'Pode aceitar −3 no Acerto para receber +5 de Dano.',repeatable:true},
  {id:'ataque-descuidado',name:'Ataque Descuidado',minLevel:1,description:'Recebe Vantagem nos ataques do turno, mas ataques contra você também têm Vantagem.',repeatable:true},
  {id:'mestre-escudos',name:'Mestre de Escudos',minLevel:1,description:'Com escudo dominado, soma o BP inteiro à Defesa em vez de metade arredondada para cima.',repeatable:true,automation:'shield'},
  {id:'iniciado-magia',name:'Iniciado em Magia',minLevel:1,description:'Aprende 2 truques mágicos simples, independentemente da origem divina.',repeatable:true},
  {id:'adepto-magico',name:'Adepto Mágico',minLevel:60,description:'Permite ensinar magias já conhecidas a outros semideuses, conforme as regras de Magia.',repeatable:true}
];
